# Generated by Django 5.2.5 on 2025-09-03 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Boots'), ('ball', 'Ball'), ('accessory', 'Accessory'), ('merch', 'Merchandise')], default='jersey', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
